apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: intemo-kafka-cluster
spec:
  kafka:
    version: 3.5.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

      - name: tls
        port: 9093
        type: internal
        tls: true

      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    storage:
        type: persistent-claim
        size: 8Gi
    resources:
      requests:
        cpu: 90m
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 2Gi
    resources:
      requests:
        cpu: 50m
        
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 200m
          memory: 200Mi
        limits:
          cpu: 500m
          memory: 300Mi